services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fork-star-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/fork_and_star_backend/.fork_env
    volumes:
      - ./backend/fork_and_star_backend/secrets:/app/secrets:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fork-star-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fork-star-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fork-star-network

networks:
  fork-star-network:
    driver: bridge