services:
  - type: web
    name: fork-and-star-backend
    env: docker
    repo: https://github.com/AsteriodBlues/fork-and-star
    branch: main
    rootDir: backend/fork_and_star_backend
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000